#!/bin/bash


if [ $# -eq 0  ]
then
	echo "NUmar insuficient de argumente"
	exit 1
fi


DIR=$1



for X in `find $1 -type f -name "*.txt"`
do
	if [ `cat $X|wc -l` -lt 6  ];then
		
		cat $X

	else
		cat $X| head -n 3
		cat $X| tail -n 3


	fi


done
